# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Christianne's Corner
email: cbarnes042993@gmail.com
description: >-
    A blog about a child raising, husband wrangling, 
    beautiful mother and her attempts to save the world with scrapebooking!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://christiannescorner.jandcb.com" # the base hostname & protocol for your site, e.g. http://example.com

# Github Config
github_username:  jmbarnes1987
github_repo: jandcb.com

# Build settings
markdown: kramdown #NOTE: kramdown is a markdown library. look into other markdown libraries, such as RDiscount
# theme: minima
theme: jekyll-athena
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# misc variables
my_name: Jacob barnes


#Not sure what I was doing below, take better notes. Regardless, using jaccobbarnes as the test site now.
#NOTE: not sure if the following is necessary, test
# defaults:
#   - scope:
#       path: "assets/img"
#     values:
#       image: true

#testing permalink settings
# permalink: /articles/:title