title: Christianne's Corner
email: cbarnes042993@gmail.com
description: >-
  A blog about a child raising, husband wrangling, beautiful mother and her
  attempts to save the world with scrapbooking!
baseurl: ''
url: christiannescorner.jandcb.com
twitter_username: ''
github_username: ''
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - ''
